# version: '2'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181    
#     networks:
#       - kafka-network

#   kafka:
#       image: confluentinc/cp-kafka:latest
#       ports:
#         - "9092:9092"
#       environment:
#         KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
#         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#         KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://[::]:9092 
#         KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#         KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
#       networks:
#         - kafka-network
# networks:
#   kafka-network:
#     driver: bridge


version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1